image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      sbt compile
    command: |
      sbt ~compile
vscode:
  extensions:
    - scalameta.metals
    # - smithy # install the extension from the vsix file in the bin folder